<h1>Edit Meetup</h1>

<?php
$form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>
<div class="form-group">
    <?= $this->formRow($form->get('title')) ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get('description')) ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get('beginningDate')) ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get('endDate')) ?>
</div>
<div class="form-group">
    <?= $this->formInput($form->get('submit')) ?>
</div>

<?= $this->form()->closeTag($form); ?>